server:
  port: ${SERVER_PORT}

spring:
  config:
    import: optional:.env

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: http://localhost:8080/login/oauth2/code/google
        provider:
          google:
            user-name-attribute: sub
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME}

  jackson: #enum ?? ????
    mapper:
      accept-case-insensitive-enums: true
  jpa:
    hibernate:
      ddl-auto: update

    show-sql: false
    properties:
      hibernate:
        format_sql: true

    servlet:
      multipart:
        max-file-size: 20MB
        max-request-size: 20MB
    web:
      resources:
        static-locations: file:./uploads/,classpath:/static/

file:
  upload-dir: uploads
  profile-images-dir: static/profileimages

jwt:
  access:
    secret: ${JWT_ACCESS_SECRET}
  refresh:
    secret: ${JWT_REFRESH_SECRET}